basePath: /api
host: localhost:8080
info:
  contact: {}
  title: GSES3 BTC application
  version: 1.0.0
paths:
  /rate:
    get:
      description: Запит має повертати поточний курс BTC до UAH використовуючи будь-який
        third party сервіс з публічним АРІ
      operationId: rate
      produces:
      - application/json
      responses:
        "200":
          description: Повертається актуальний курс BTC до UAH
          schema:
            type: integer
        "400":
          description: Invalid status value
      summary: Отримати поточний курс BTC до UAH
      tags:
      - rate
  /sendEmails:
    post:
      description: Запит має отримувати актуальний курс BTC до UAH за допомогою third-party
        сервісу та відправляти його на всі електронні адреси, які були підписані раніше.
      operationId: sendEmails
      produces:
      - application/json
      responses:
        "200":
          description: E-mailʼи відправлено
      summary: Відправити e-mail з поточним курсом на всі підписані електронні пошти.
      tags:
      - subscription
  /subscribe:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Запит має перевірити, чи немає данної електронної адреси в поточній
        базі даних (файловій) і, в разі її відсутності, записувати її. Пізніше, за
        допомогою іншого запиту ми будемо відправляти лист на ті електронні адреси,
        які будуть в цій базі.
      operationId: subscribe
      parameters:
      - description: Електронна адреса, яку потрібно підписати
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: E-mail додано
        "400":
          description: BadRequest
        "409":
          description: Повертати, якщо e-mail вже є в базі даних (файловій)
      summary: Підписати емейл на отримання поточного курсу
      tags:
      - subscription
schemes:
- http
swagger: "2.0"
